$color = rgba(13, 17, 23, 1)
$inner_color = rgb(10, 58, 204)
$outer_color = rgb(10, 58, 204)
$font_color = rgba(240, 246, 252, 1)
$placeholder_color = rgba(240, 246, 252, 0.7)
$check_color = rgb(27, 193, 38)
